# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-26 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190327_0415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodschannel',
            options={'ordering': ['group_id', 'sequence'], 'verbose_name': '商品频道', 'verbose_name_plural': '商品频道'},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['id'], 'verbose_name': '商品SKU', 'verbose_name_plural': '商品SKU'},
        ),
    ]
