# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200426_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
    ]
