# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-16 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200428_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spu',
            old_name='brand',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='spu',
            old_name='category1',
            new_name='category1_id',
        ),
        migrations.RenameField(
            model_name='spu',
            old_name='category2',
            new_name='category2_id',
        ),
        migrations.RenameField(
            model_name='spu',
            old_name='category3',
            new_name='category3_id',
        ),
    ]
