# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-17 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20200516_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificationoption',
            old_name='spec',
            new_name='spec_id',
        ),
    ]
