# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-17 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20200517_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spuspecification',
            old_name='spu',
            new_name='spu_id',
        ),
    ]
