# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-17 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20200517_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default='', upload_to='', verbose_name='Logo图片'),
        ),
    ]
