# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-21 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20200521_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spuspecification',
            old_name='spu_id_id',
            new_name='spu_id',
        ),
    ]
